### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by wqingzex** [darkonhub/darkon#49]
I am using tensorflow 1.6, when `import darkon`, it turns out that
```
/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/__init__.py in <module>()
     20 
     21 # Add projects here, they will show up under tf.contrib.
---> 22 from tensorflow.contrib import batching
     23 from tensorflow.contrib import bayesflow
     24 from tensorflow.contrib import cloud

ImportError: cannot import name batching
```

**Comment by zironycho** [comment]
Hi, @qingzew 
Thank you for reporting this issue. I will check and update soon for tensorflow 1.6.

**Comment by zironycho** [comment]
@qingzew 
I installed the darkon with tensorflow 1.6, and import darkon packge. It worked.
I tested on `Ubuntu 16.04` with `python2.7`, `python3.5`.

Could you give me more specific your environment such as OS, python packages, and so on?
I think your problem looks like tensorflow package it self.

If you can reinstall your tensorflow, could you do that?

**Comment by wqingzex** [comment]
Hi @zironycho 
this is more info:
ubuntu 16.04
python 2.7
tensorflow 1.6 build from source

I check it again, it is the problem of `--config=monolithic`, when I build:
```
bazel build --config=opt --config=cuda --config=monolithic //tensorflow/tools/pip_package:build_pip_package
```
it will be error, but
```
bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```
will be ok

I understand `--config=monolithic` is static linker, something is wrong

**Comment by zironycho** [comment]
Hi @qingzew .
I'm glad to hear you solve the problem. If you don't have more concern, could you please close this issue?
Thank you
